/**
 * Progressive Loading Example
 *
 * This example demonstrates how to use Carnet for progressive loading of skills,
 * toolsets, and tools. This pattern is useful when you want to:
 *
 * 1. Give LLMs initial context with core skills loaded
 * 2. Allow LLMs to request additional skills as needed
 * 3. Minimize initial prompt size while maintaining full functionality
 *
 * The example shows how an app developer would:
 * - Load initial skills and generate agent prompts
 * - Create wrapper tools that use Carnet's progressive loading APIs
 * - Implement a chat/tool-calling loop that loads content on demand
 */

import { Carnet } from '../src/lib/index'

// ============================================================================
// SETUP: Initialize Carnet with variable injection support
// ============================================================================

async function setupCarnet() {
  // Load the manifest (generated by carnet CLI)
  const carnet = await Carnet.fromManifest('./dist/carnet.manifest.json', {
    // Inject custom variables at runtime
    variables: {
      THEME_JSON_SCHEMA: JSON.stringify({
        type: 'object',
        properties: { color: { type: 'string' } },
      }),
      PAGE_ATTRIBUTES_SCHEMA: JSON.stringify({
        type: 'object',
        properties: { title: { type: 'string' } },
      }),
    },
    // Only allow environment variables with these prefixes
    envPrefixes: ['CARNET_', 'PUBLIC_'],
  })

  return carnet
}

// ============================================================================
// STEP 1: Generate Initial Agent Prompt with Skills
// ============================================================================

async function generateAgentPromptExample() {
  const carnet = await setupCarnet()

  // Generate a complete, LLM-ready prompt for the agent
  // This includes:
  // - Agent's main instructions
  // - Full content of initial skills
  // - Metadata catalog of available on-demand skills
  // - Instructions on how to load skills dynamically
  const agentPrompt = carnet.generateAgentPrompt('coder', {
    // Optional: include/exclude specific sections
    includeInitialSkills: true,
    includeSkillCatalog: true,
    // Optional: override variables for this prompt
    variables: {
      THEME_JSON_SCHEMA: 'custom schema',
    },
  })

  console.log('=== AGENT PROMPT ===')
  console.log(agentPrompt.content)
  console.log('\n=== METADATA ===')
  console.log('Agent:', agentPrompt.agent.name)
  console.log('Initial Skills:', agentPrompt.initialSkills.map((s) => s.name))
  console.log('Available Skills:', agentPrompt.availableSkills.map((s) => s.name))
}

// ============================================================================
// STEP 2: Tools for Progressive Loading (App Developer Implements These)
// ============================================================================

/**
 * Example tool implementations that app developers would create.
 * These are wrappers around Carnet's APIs that LLMs can call to load content on demand.
 */

async function createCarnetTools(carnet: Carnet) {
  return {
    /**
     * Tool for loading a skill by name
     * Returns the full skill content with variable injection
     */
    loadSkill: {
      name: 'loadSkill',
      description: 'Load a skill by name to get its full content and instructions',
      parameters: {
        type: 'object',
        properties: {
          skillName: {
            type: 'string',
            description: 'The name of the skill to load',
          },
        },
        required: ['skillName'],
      },
      execute: async (skillName: string) => {
        try {
          const content = carnet.getSkillContent(skillName, {
            // Get full content with variables injected
            raw: false,
          })

          return {
            success: true,
            content,
            metadata: carnet.getSkillMetadata(skillName),
          }
        } catch (error) {
          return {
            success: false,
            error: `Failed to load skill: ${error instanceof Error ? error.message : String(error)}`,
          }
        }
      },
    },

    /**
     * Tool for listing available toolsets for a skill
     */
    listSkillToolsets: {
      name: 'listSkillToolsets',
      description: 'List all toolsets available in a skill',
      parameters: {
        type: 'object',
        properties: {
          skillName: {
            type: 'string',
            description: 'The name of the skill',
          },
        },
        required: ['skillName'],
      },
      execute: async (skillName: string) => {
        try {
          const toolsets = carnet.listSkillToolsets(skillName)
          return {
            success: true,
            toolsets: toolsets.map((t) => ({
              name: t.name,
              description: t.description,
              toolCount: t.tools.length,
            })),
          }
        } catch (error) {
          return {
            success: false,
            error: `Failed to list toolsets: ${error instanceof Error ? error.message : String(error)}`,
          }
        }
      },
    },

    /**
     * Tool for loading a toolset and listing its tools
     */
    loadToolset: {
      name: 'loadToolset',
      description: 'Load a toolset to get its instructions and available tools',
      parameters: {
        type: 'object',
        properties: {
          toolsetName: {
            type: 'string',
            description: 'The name of the toolset to load',
          },
        },
        required: ['toolsetName'],
      },
      execute: async (toolsetName: string) => {
        try {
          const content = carnet.getToolsetContent(toolsetName)
          const tools = carnet.listToolsetTools(toolsetName)

          return {
            success: true,
            content,
            availableTools: tools.map((t) => ({
              name: t.name,
              description: t.description,
            })),
          }
        } catch (error) {
          return {
            success: false,
            error: `Failed to load toolset: ${error instanceof Error ? error.message : String(error)}`,
          }
        }
      },
    },

    /**
     * Tool for loading a specific tool by name
     */
    loadTool: {
      name: 'loadTool',
      description: 'Load a specific tool to get its full documentation and usage',
      parameters: {
        type: 'object',
        properties: {
          toolName: {
            type: 'string',
            description: 'The name of the tool to load',
          },
        },
        required: ['toolName'],
      },
      execute: async (toolName: string) => {
        try {
          const content = carnet.getToolContent(toolName)
          const metadata = carnet.getToolMetadata(toolName)

          return {
            success: true,
            metadata,
            content,
          }
        } catch (error) {
          return {
            success: false,
            error: `Failed to load tool: ${error instanceof Error ? error.message : String(error)}`,
          }
        }
      },
    },

    /**
     * Tool for listing all available skills for an agent
     * (useful for discovery)
     */
    listAvailableSkills: {
      name: 'listAvailableSkills',
      description: 'List all skills available to the agent (both initial and on-demand)',
      parameters: {
        type: 'object',
        properties: {
          agentName: {
            type: 'string',
            description: 'The name of the agent',
          },
        },
        required: ['agentName'],
      },
      execute: async (agentName: string) => {
        try {
          const skills = carnet.listAvailableSkills(agentName)
          return {
            success: true,
            skills: skills.map((s) => ({
              name: s.name,
              description: s.description,
              toolsets: s.toolsets,
            })),
          }
        } catch (error) {
          return {
            success: false,
            error: `Failed to list skills: ${error instanceof Error ? error.message : String(error)}`,
          }
        }
      },
    },
  }
}

// ============================================================================
// STEP 3: Simulated Chat Loop with Progressive Loading
// ============================================================================

interface ToolCall {
  toolName: string
  args: Record<string, string>
}

async function simulateChatWithProgressiveLoading() {
  const carnet = await setupCarnet()
  const tools = await createCarnetTools(carnet)

  // Generate initial agent prompt
  const agentPrompt = carnet.generateAgentPrompt('coder')

  console.log('=== INITIAL AGENT PROMPT ===')
  console.log(agentPrompt.content)
  console.log('\n')

  // Simulate tool calls from LLM
  const simulatedToolCalls: ToolCall[] = [
    {
      toolName: 'listAvailableSkills',
      args: { agentName: 'coder' },
    },
    {
      toolName: 'loadSkill',
      args: { skillName: 'components' },
    },
    {
      toolName: 'listSkillToolsets',
      args: { skillName: 'components' },
    },
  ]

  for (const call of simulatedToolCalls) {
    console.log(`\n>>> LLM calls tool: ${call.toolName}`)
    console.log(`    with args: ${JSON.stringify(call.args)}`)

    const tool = tools[call.toolName as keyof typeof tools]
    if (!tool) {
      console.log(`    ERROR: Tool not found`)
      continue
    }

    try {
      // Execute the tool
      const result = await tool.execute(Object.values(call.args)[0])
      console.log(`<<< Tool returned:`)
      console.log(JSON.stringify(result, null, 2))
    } catch (error) {
      console.log(`    ERROR: ${error instanceof Error ? error.message : String(error)}`)
    }
  }
}

// ============================================================================
// STEP 4: Variable Injection Example
// ============================================================================

async function demonstrateVariableInjection() {
  const carnet = await setupCarnet()

  // Get skill content with variables injected
  const skillContent = carnet.getSkillContent('design-system', {
    variables: {
      CUSTOM_THEME: 'dark-mode',
    },
  })

  console.log('=== SKILL CONTENT WITH VARIABLES INJECTED ===')
  console.log(skillContent)

  // Get raw content (no variable injection)
  const rawContent = carnet.getSkillContent('design-system', { raw: true })

  console.log('\n=== RAW SKILL CONTENT (NO VARIABLE INJECTION) ===')
  console.log(rawContent)
}

// ============================================================================
// STEP 5: Metadata-Only Retrieval for Efficient Discovery
// ============================================================================

async function demonstrateMetadataRetrieval() {
  const carnet = await setupCarnet()

  console.log('=== SKILL METADATA (LIGHTWEIGHT) ===')
  const skillMetadata = carnet.getSkillMetadata('components')
  console.log(skillMetadata)
  // Output: { name: 'components', description: '...', toolsets: [...] }
  // No large content payload

  console.log('\n=== TOOLSET METADATA (LIGHTWEIGHT) ===')
  const toolsetMetadata = carnet.listSkillToolsets('components')
  toolsetMetadata.forEach((t) => {
    console.log(`  - ${t.name}: ${t.description} (${t.tools.length} tools)`)
  })

  console.log('\n=== TOOL METADATA (LIGHTWEIGHT) ===')
  const toolMetadata = carnet.listToolsetTools('sdk-components')
  toolMetadata.forEach((t) => {
    console.log(`  - ${t.name}: ${t.description}`)
  })
}

// ============================================================================
// MAIN: Run examples
// ============================================================================

async function main() {
  console.log('╔════════════════════════════════════════════════════════════════╗')
  console.log('║      CARNET PROGRESSIVE LOADING EXAMPLE                        ║')
  console.log('╚════════════════════════════════════════════════════════════════╝\n')

  try {
    // Note: These examples assume the carnet manifest exists
    // Run `carnet build` first to generate the manifest

    console.log('1. Generate Agent Prompt Example')
    console.log('─'.repeat(60))
    // await generateAgentPromptExample()

    console.log('\n2. Chat Loop with Progressive Loading')
    console.log('─'.repeat(60))
    // await simulateChatWithProgressiveLoading()

    console.log('\n3. Variable Injection Example')
    console.log('─'.repeat(60))
    // await demonstrateVariableInjection()

    console.log('\n4. Metadata Retrieval Example')
    console.log('─'.repeat(60))
    // await demonstrateMetadataRetrieval()

    console.log('\n\n✓ Examples completed!')
    console.log('\nKey Takeaways:')
    console.log('1. Use generateAgentPrompt() to create initial LLM context')
    console.log('2. Implement tool wrappers around Carnet APIs for LLM-accessible loading')
    console.log('3. Use metadata methods for efficient discovery without full content')
    console.log('4. Variable injection happens automatically during content retrieval')
    console.log('5. Set raw: true to get uninjected content for special use cases')
  } catch (error) {
    console.error('Error:', error)
  }
}

// Uncomment to run:
// main().catch(console.error)

export {
  setupCarnet,
  generateAgentPromptExample,
  createCarnetTools,
  simulateChatWithProgressiveLoading,
  demonstrateVariableInjection,
  demonstrateMetadataRetrieval,
}
